pgvector-ivfflat-cohere-1m-1k:
  indexType: ivfflat
  dataset: cohere-1m-cos
  datasetType: parquet
  metric: cos
  lists: 1000  # ~sqrt(1M)
  maintenance_work_mem: 4GB
  pg_parallel_workers: 32
  top: 10
  benchmarks:
    "20":  { probes: 20 }
    "40":  { probes: 40 }
    "80":  { probes: 80 }
    "150": { probes: 150 }
    "300": { probes: 300 }