edb_vectorplus-ivfplus-openai-20k-141:
  indexType: ivfplus
  dataset: openai-20k-cos
  datasetType: parquet
  metric: cos
  lists: 141  # ~sqrt(20k)
  maintenance_work_mem: 1GB
  pg_parallel_workers: 1
  top: 10
  benchmarks:
    "30":  { probes: 30 }
    "141": { probes: 141 }
