edb_vectorplus-ivfplus-laion-5k-71:
  indexType: ivfplus
  dataset: laion-5k-ip
  datasetType: parquet
  metric: ip
  lists: 71  # ~sqrt(5k)
  maintenance_work_mem: 1GB
  pg_parallel_workers: 1
  top: 10
  benchmarks:
    "16": { probes: 16 }
    "71": { probes: 71 }
