edb_vectorplus-ivfplus-cohere-10m-3162:
  indexType: ivfplus
  dataset: cohere-10m-cos
  datasetType: parquet
  metric: cos
  lists: 3162  # ~sqrt(10M), same as pgvector-ivfflat-3k
  maintenance_work_mem: 24GB
  pg_parallel_workers: 32
  top: 10
  benchmarks:
    "30":  { probes: 30 }
    "60":  { probes: 60 }
    "120": { probes: 120 }
    "200": { probes: 200 }
    "400": { probes: 400 }
