edb_vectorplus-ivfplus-openai-10k-100:
  indexType: ivfplus
  dataset: openai-10k-cos
  datasetType: parquet
  metric: cos
  lists: 100
  maintenance_work_mem: 1GB
  pg_parallel_workers: 1
  top: 10
  benchmarks:
    "20":  { probes: 20 }
    "100": { probes: 100 }
