edb_vectorplus-ivfplus-openai-1k-32:
  indexType: ivfplus
  dataset: openai-1k-cos
  datasetType: parquet
  metric: cos
  lists: 32  # ~sqrt(1k)
  maintenance_work_mem: 1GB
  pg_parallel_workers: 1
  top: 10
  benchmarks:
    "8":  { probes: 8 }
    "32": { probes: 32 }
